LineLength:
  Enabled: true
  Max: 120
MethodLength:
  Enabled: true
  Max: 50
ClassLength:
  Enabled: true
  Max: 250
AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: true
  Max: 15
PerceivedComplexity:
  Enabled: false
RegexpLiteral:
  Enabled: false
  EnforcedStyle: slashes
  SupportedStyles: slashes
CyclomaticComplexity:
  Enabled: true
  Max: 20
AllCops:
  TargetRubyVersion: 1.9.3
  Include:
    - 'lib/**'
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
