language: ruby
rvm:
- 1.9.3
- 2.1.7
sudo: false
cache: bundler
deploy:
  api_key:
    secure: zSbrkJK/6pVtjWIxrJ+HuBrffibwoijfpqUX5TkFJ6HGhSze4flOvkm5i5GrRT35m9olhtFU5QX1FD4EOmwCN0Dd0J/eaGxtcIOjb4KhANUSckJzwDsrwzjw8ut9m7MOu29vksRYi3kvY5TGpB/mr3IRG5siCQAH+I2RIpT8DsZkrKae8q507mDk3uvggKgcEOxiICeva0/bJLKrenIrfP+1bUuucCYPaPh3cPkFRj/z80phLJyAgE71yqtsFD0mnj8phNhaK0jw0g7d2Ic6HKKZds08p/3VMjYvFgRsaeqdqAbZcXdH866Zij6I5IuNLHGwZvHcMLPYukFLvXCER1ZRbbXmK0eb5Qt406K7qRN3pXGtcSsSKf7booZ0+JBKk7tR75Xt+BUrLtQs6y91Ugphbf94cv6bsLqpv97xKAAwAAH62IZz2a8h1LZiud3hSrWC4O19MidCdZoALhZrH+5DyFALwIScilKDsl4GsVY5/Bt/Zt+NzuKzYXrwVJo4c10k3ScU2WNFoKe6iJuia7LnpdgLdW28KGCzxZQQ3s0Of5GyheB/yqI5mKmmkg//lPcAlklZ/4UvsdBh5hSPg/7ez3AqAOuJ6dCaMJATZDO4nXxfUaHPm4Hsp4QdwG0FHTsbUMXjRgrjKyQi4IbUCRM42gt5/UMuuYOdv4+uNQY=
  on:
    tags: true
    branch: master
